name: monet-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - cartopy
  - dask
  - matplotlib
  - h5py
  - netcdf4
  - numpy
  - pandas
  - pillow>=9.1.0
  - pip
  - seaborn
  - xarray
  - pytest
  - pytest-cov
  - pooch
  - esmpy
  - scipy
  - pip:
      - xregrid
      - pytspack
      - monet-stats
